version: '3.8'

services:
  auth-service:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: auth-service
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://localhost:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: "true"
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm", "--verbose" ]
    depends_on:
      - mysql
    network_mode: host
    volumes:
      - ./keycloak:/tmp/keycloak
  mysql:
    image: mysql:8.0.26
    container_name: keycloak-db
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./databases/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    network_mode: "host"
    restart: always